pagopa/pagopa-receipt-pdf-service

- openapi/openapi.json
- src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
- src/main/resources/application.properties
- src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
- Modified fiscal_code header in query_param
Run unit test and invoked the APIs
expected)
> fix: Fiscal code param

- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/resources/application.properties
- fixed info endpoint response
Make app info available on status page
> [PRDP-85] fix: Status info response

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- Removed G1 garbage collector option from java options
Fix application startup
expected)
> [PRDP-85] fix: Remove gc option

- src/main/resources/application.properties
> fix: deploy

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- src/main/resources/application.properties
- Added app_name env
Fix service deploy
expected)
> [PRDP-85] fix: Deploy

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- removed G1 garbage collector
expected)
> [PRDP-85] fix: Removed G1 gc option

- Dockerfile
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/resources/__logback.xml
- src/main/resources/application.properties
- src/main/resources/logback.xml
- Introducing logback configuration
- Changing logging to use SL4J
- Updated helm chart values
- Updated Dockerfile
expected)
> [PRDP-95] Introducing APM elk agent and logback.xml

- Dockerfile
- helm/values-dev.yaml
> fix: Otel deploy

- helm/values-uat.yaml
> fix: Uat deploy

- .devops/performance-test-pipelines.yml
> fix: Perf pipe

- helm/values-dev.yaml
- helm/values-uat.yaml
> fix: Dev deploy

- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
> fix: Chk get receipt

- src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/AppErrorCodeEnum.java
- src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
- src/test/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImplTest.java
- Modified fiscal code checks
Modified fiscal code check to allow the scenario with payer fiscal code null
Run unit tests
expected)
> [PRDP-109] fix: Fix fiscal code checks

- .github/workflows/code_review.yml
- .github/workflows/integration_test.yml
- .identity/00_data.tf
- .identity/03_github_environment.tf
- Added integration test action
Run integration tests on all environment
expected)
> [PRDP-112] feat: Add integration test action

- integration-test/src/features/receipt_pdf_service.feature
- src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/AppErrorCodeEnum.java
- src/main/java/it/gov/pagopa/receipt/pdf/service/exception/InvalidFiscalCodeHeaderException.java
- src/main/java/it/gov/pagopa/receipt/pdf/service/exception/mapper/ExceptionMapper.java
- src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
- src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
- added check on fiscal code length (equals to 16)
- added unit tests
- refactor some class
Improve fiscal_code field check and avoid the possibility to pass empty value
Added unit tests
expected)
> [PRDP-116] fix: Improved fiscal code checks

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> feat: Review request-limit aks

- .github/workflows/integration_test.yml
- .identity/00_data.tf
- .identity/03_github_environment.tf
- added webhook url to identity
- enabled integration tests result notification on slask
Add  integration tests result notification on slask
expected)
> [PRDP-117] feat: Add slack webhook to integration tests action

- .github/workflows/integration_test.yml
> fix integration test

- .github/workflows/integration_test.yml
> fix action

- .github/workflows/integration_test.yml
> fix action and cron

- performance-test/src/test-types/constant.json
> fix: Test constant

- src/main/java/it/gov/pagopa/receipt/pdf/service/model/Receipt.java
Added receipt's timestamps
[Issue PRDP-135](https://pagopa.atlassian.net/browse/PRDP-135?atlOrigin=eyJpIjoiMmVkZGM2Mzg3MDMzNDNkMmJkMjQ5NTkzY2QwYzQzZjgiLCJwIjoiaiJ9)
> [PRDP-135] Added receipt's timestamps

- helm/values-uat.yaml
- Decreased max replica in UAT chart to 1
Avoid scaling
> feat: Decrease max replica in UAT chart

- .github/workflows/create_dashboard.yml
- .opex/env/dev/backend.ini
- .opex/env/dev/backend.tfvars
- .opex/env/dev/config.yaml
- .opex/env/dev/terraform.tfvars
- .opex/env/prod/backend.tfvars
- .opex/env/prod/config.yaml
- .opex/env/prod/terraform.tfvars
- .opex/env/uat/backend.ini
- .opex/env/uat/backend.tfvars
- .opex/env/uat/config.yaml
- .opex/env/uat/terraform.tfvars
- added create dashboard action
- configured opex
Create dashboard and alerts
expected)
> [PRDP-25] feat: Add dashboard and configured opex

- .opex/pdf-receipt-service/env/prod/config.yaml
> fix: Dash prod

- src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
- src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
- Deleted fiscal code from logs
[Issue PRDP-159](https://pagopa.atlassian.net/browse/PRDP-159?atlOrigin=eyJpIjoiZmFjODkyM2ViNjUwNGMzNzk3ZjM2ZDA0NGM1MDQ1MDMiLCJwIjoiaiJ9)
Fiscal codes were logged when specific errors occured
expected)
> [PRDP-159] Deleted fiscal code from logs

- src/main/java/it/gov/pagopa/receipt/pdf/service/model/receipt/Receipt.java
- Added section in receipt to store error that occur for payer elaboration
> [PRDP-164] feat: Added specific section for payer error in receipt

- .github/maven_code_review/action.yml
- Dockerfile
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- added application insights agent
- fix code coverage report path for main branch
Send logs to application insights
Fix coverage on main branch
expected)
> [PRDP-172] feat: Add application insights agent

- helm/values-prod.yaml
- Fixed tokenizer path in prod
Tokenizer path in helm prod was wrong
expected)
> [fix] Fixed tokenizer path in prod

- helm/values-prod.yaml
> fix pdf api path

- helm/values-prod.yaml
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability by deploying at least one pod per availability zone.
> [PRDP-235] feat: Add pod antiAffinity

- src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/ReceiptStatusType.java
- added missing receipt status
expected)
> fix: Add missing receipt status

- .opex/pdf-receipt-service/env/prod/config.yaml
- .opex/pdf-receipt-service/env/uat/config.yaml
- Update service endpoints opex param to be more flexible on alerts
- Avoiding false positives on alert params for response time
expected)
> feat: updated opex params

- src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
- src/test/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImplTest.java
- Updated checks for anonym checks
https://pagopa.atlassian.net/browse/PRDP-305
expected)
> [PRDP-305] feat: relaxed checks for anonym debtors

- src/main/java/it/gov/pagopa/receipt/pdf/service/model/receipt/Receipt.java
- added is cart flag
added field as descripted in analisys
expected)
> [PRDP-286] feat: Add isCart field to receipt model

- .github/workflows/create_dashboard.yaml
- .opex/pdf-receipt-service-apimv2/env/prod/backend.ini
- .opex/pdf-receipt-service-apimv2/env/prod/backend.tfvars
- .opex/pdf-receipt-service-apimv2/env/prod/config.yaml
- .opex/pdf-receipt-service-apimv2/env/prod/terraform.tfvars
> chore: Alert OPEX x apim V2

- .github/maven_code_review/action.yml
- .github/workflows/deploy_with_github_runner.yml
- .github/workflows/release_deploy.yml
- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/99_main.tf
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- openapi/openapi.json
- pom.xml
- Implemented new runner
- Implemented workload identity with helm version 7.5.0
[PIDM-482](https://pagopa.atlassian.net/browse/PIDM-482)
[PIDM-482]: https://pagopa.atlassian.net/browse/PIDM-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: [PIDM-482] Implement workload identity & new runner
